"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-27 12:30:08.885021

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""
from pycatia3dx.sketcher.curve_2d import Curve2D


class Parabola2D(Curve2D):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-27 12:30:08.885021)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     CATSketcherIDLItf.GeometricElement
                |                         CATSketcherIDLItf.Geometry2D
                |                             CATSketcherIDLItf.Curve2D
                |                                 Parabola2D
                | 
                | Class defining an parabola in 2D Space.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    @property
    def focal_distance(self) -> float:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-27 12:30:08.885021)
                | Property FocalDistance() As double (Read Only)
                |     Returns the focal distance of the parabola in 2D space.
                | 
                |     Returns:
                |         oFocal The focal distance of the parabola

        :return: float
        """

        return self.com_object.FocalDistance

    def get_axis(self) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-27 12:30:08.885021)
                | Sub GetAxis(CATSafeArrayVariant oAxis)
                |     Returns the axis vector direction of the parabola in 2D
                |     space.
                | 
                |     Parameters:
                | 
                |         oAxis
                | 
                |               oAxis[0]: The X coordinate of the axis vector
                |               direction
                |               oAxis[1]: The Y coordinate of the axis vector
                |               direction

        :return: tuple
        """
        return self.com_object.GetAxis()
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'get_axis'
        # vba_code = """
        # Public Function get_axis(parabola2_d)
        #     Dim oAxis (2)
        #     parabola2_d.GetAxis oAxis
        #     get_axis = oAxis
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def get_center(self) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Sub GetCenter(CATSafeArrayVariant oCenter)
                |     Returns the center of the parabola in 2D space.
                |
                |     Parameters:
                |
                |         oCenter
                |
                |               oCenter[0]: The X Coordinate of the center point of the
                |               parabola
                |               oCenter[1]: The Y Coordinate of the center point of the
                |               parabola

        :return: tuple
        """
        return self.com_object.GetCenter()
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'get_center'
        # vba_code = """
        # Public Function get_center(parabola2_d)
        #     Dim oCenter (2)
        #     parabola2_d.GetCenter oCenter
        #     get_center = oCenter
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def set_data(self, i_center_x: float, i_center_y: float, i_axis_x: float, i_axis_y: float,
                 i_focal_distance: float) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-27 12:30:08.885021)
                | Sub SetData(double iCenterX,double iCenterY,double iAxisX,double iAxisY,double
                | iFocalDistance)
                |     Modifies the caracteristics of the parabola.
                | 
                |     Parameters:
                | 
                |         iCenterX
                |             The X Coordinate of the parabola center 
                |         iCenterY
                |             The Y Coordinate of the parabola center 
                |         iAxisX
                |             The X coordinate of the axis vector direction 
                |         iAxisY
                |             The Y coordinate of the axis vector direction 
                |         iFocalDistance
                |             The focal distance of the parabola

        :param float i_center_x:
        :param float i_center_y:
        :param float i_axis_x:
        :param float i_axis_y:
        :param float i_focal_distance:
        :return: None
        """
        return self.com_object.SetData(i_center_x, i_center_y, i_axis_x, i_axis_y, i_focal_distance)

    def __repr__(self):
        return f'Parabola2D(name="{self.name}")'
