TEST_CATPART_ONE = "pycatia3DX - Test - Part One"
TEST_CATPART_ONE_DESCRIPTION = "1.0"

geom_set_arcs = "construction_arcs"
geom_set_cylinders = "construction_cylinders"
geom_set_lines = "construction_lines"
geom_set_planes = "construction_planes"
geom_set_points = "construction_points"
geom_set_sketches = "construction_sketches"
geom_set_splines = "construction_splines"
geom_set_surfaces = "construction_surfaces"
