"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""

from pycatia3dx.system.any_object import AnyObject
from pycatia3dx.dnb_igp_olp_use.olp_controller import OLPController


class OLPGun(AnyObject):

    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     OlpGun
                | 
                | Interface for accessing a gun's properties.
                | 
                | This interface can only be used by a translator within the Robotics Off-line
                | Programming (OLP) Download or Upload command.
                | This object can be retrieved from a OlpResourceControlDevice.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    @property
    def attached_robot(self) -> OLPController:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property AttachedRobot() As OlpController (Read Only)
                |     The robot that uses this gun.

        :return: OLPController
        """

        return OLPController(self.com_object.AttachedRobot)

    @property
    def controller(self) -> OLPController:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property Controller() As OlpController (Read Only)
                |     The controller for this gun.

        :return: OLPController
        """

        return OLPController(self.com_object.Controller)

    @property
    def index(self) -> int:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property Index() As long (Read Only)
                |     Get/Set the gun index.
                |     If no gun index was assigned by the user, a unique index will automatically
                |     be generated by the infrastructure.

        :return: int
        """

        return self.com_object.Index

    @property
    def joint_index(self) -> int:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property JointIndex() As long (Read Only)
                |     The joint in the Controller that is moved for this gun.

        :return: int
        """

        return self.com_object.JointIndex

    @property
    def sub_type(self) -> str:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property SubType() As CATBSTR
                |     Get the gun technology.
                |     This is the gun technology used for the application. Each application uses its own sub types. For Paint the options are : "Air" and "Electrostatic". For SpotWeld the options are : "Servo" and "Air".

        :return: str
        """

        return self.com_object.SubType

    @sub_type.setter
    def sub_type(self, value: str):
        """
        :param str value:
        """

        self.com_object.SubType = value

    @property
    def type(self) -> str:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property Type() As CATBSTR (Read Only)
                |     Get the gun application.
                |     Currently only "Paint" and "SpotWeld" are supported, but more may be added
                |     in the future (e.g. "Rivet", etc). 

        :return: str
        """

        return self.com_object.Type

    def __repr__(self):
        return f'OLPGun(name="{ self.name }")'
