"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""
from pycatia3dx import CatImportFromDrawingOption
from pycatia3dx.system.any_object import AnyObject


class Layout2DServices(AnyObject):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     Layout2DServices

    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    def import_from_drawing(self, i_objects: tuple, i_option: CatImportFromDrawingOption, o_results: tuple) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Sub ImportFromDrawing(CATSafeArrayVariant iObjects,CatImportFromDrawingOption
                | iOption,CATSafeArrayVariant oResults)
                |     Import in a 2DLayout a drawing view array. Drawing views with generative
                |     behavior and detail views are not managed. Views are copied in active 2DLayout
                |     sheet. Last copied view is set as active view.
                |
                |     Parameters:
                |
                |         iObjects
                |             [in] The array of views to copy
                |         iOption
                |             [in] This parameter is not used. All view content is copied and
                |             isolated.
                |         oResults
                |             [inout] The array of views copied in 2DLayout
                |
                |     Example:
                |         The following example retrieves this service from
                |         2DLayout
                |
                |          Dim myPart As CATIAPart
                |          Set myPart = CATIA.ActiveEditor.ActiveObject
                |          Dim MyRoot As Layout2DRoot
                |          Set MyRoot = myPart.GetItem("CATLayoutRoot")
                |          Dim layoutServices As Layout2DServices
                |          Set layoutServices = MyRoot.GetItem("CATLayout2DServices")

        :param tuple i_objects:
        :param CatImportFromDrawingOption i_option:
        :param tuple o_results:
        :return: None
        """
        return self.com_object.ImportFromDrawing(i_objects, i_option.com_object, o_results)
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'import_from_drawing'
        # vba_code = """
        # Public Function import_from_drawing(layout2_d_services)
        #     Dim iObjects (2)
        #     layout2_d_services.ImportFromDrawing iObjects
        #     import_from_drawing = iObjects
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def __repr__(self):
        return f'Layout2DServices(name="{self.name}")'
