"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""
from typing import Iterator

from pycatia3dx.plm_validation.marker import Marker
from pycatia3dx.system.any_object import AnyObject
from pycatia3dx.system.collection import Collection
from pycatia3dx.types.general import CATVariant


class Markers(Collection):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.Collection
                |                     Markers
                | 
                | A collection of Markers.
                | 
                | The method VALReview.GetFactory ("Markers") on the VALReview retrieves this
                | collection.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object, child_object=Marker)
        self.com_object = com_object

    def add(self, i_text: str) -> Marker:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func Add(CATBSTR iText) As Marker
                |     Adds a Marker to the collection.
                | 
                |     Parameters:
                | 
                |         iText
                |             The Marker type string 2DTEXT 2DPICTURE 2DHYPERLINK 2DAUDIO 3DTEXT
                |             3DPICTURE 3DHYPERLINK 3DAUDIO 
                | 
                |     Returns:
                |         The created marker 
                |     Example:
                | 
                |          This example creates a new Marker in the cMarkers
                |          collection.
                |          
                | 
                |          Dim cMarkers As Markers 
                |          Set cMarkers = TheVALReview.GetFactory("Markers")
                |          Dim oNewMarkerPicture As Marker
                |          Set oNewMarkerPicture = cMarkers.Add("2DPICTURE")

        :param str i_text:
        :return: Marker
        """
        return Marker(self.com_object.Add(i_text))

    def add_shape(self, i_coordinates: tuple, i_text: str) -> Marker:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Func AddShape(CATSafeArrayVariant iCoordinates,CATBSTR iText) As
                | Marker
                |     Adds a Shape Marker to the collection. The Marker drawing is defined using
                |     the coordinates of a series of points.
                |
                |     Parameters:
                |
                |         iCoordinates
                |
                |     See also:
                |         Marker.SetPositions method of the CATIAMarker object
                |     Parameters:
                |
                |         iText
                |             The Marker type string 2DLINE 2DPEN 2DCIRCLE 2DRECTANGLE 2DARROW
                |
                |
                |     Returns:
                |         oMarker The created Marker
                |     Example:
                |
                |          This example creates a new Shape Marker in the cMarkers
                |          collection.
                |
                |
                |          Dim cMarkers As Markers
                |          Set cMarkers = TheVALReview.GetFactory("Markers")
                |          Dim oNewMarkerCircle As Marker
                |          Set oNewMarkerCircle = cMarkers.AddShape(iCoordinates, "2DCIRCLE")

        :param tuple i_coordinates:
        :param str i_text:
        :return: Marker
        """
        return Marker(self.com_object.AddShape(i_coordinates, i_text))
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'add_shape'
        # vba_code = """
        # Public Function add_shape(markers)
        #     Dim iCoordinates (2)
        #     markers.AddShape iCoordinates
        #     add_shape = iCoordinates
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def item(self, i_index: CATVariant) -> AnyObject:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func Item(CATVariant iIndex) As CATBaseDispatch
                |     Returns a Marker using its index from the Markers
                |     collection.
                | 
                |     Parameters:
                | 
                |         iIndex
                |             The index or the name of the Marker to retrieve from the collection
                |             of Markers. As a numerics, this index is the rank of the Marker in the
                |             collection. The index of the first Marker in the collection is 1, and the index
                |             of the last Marker is Count. As a string, it is the name you assigned to the
                |             Marker. 
                | 
                |     Returns:
                |         The retrieved Marker 
                |     Example:
                | 
                |          This example retrieves in oMarker1 the third Marker,
                |          and in oMarker2 the Marker named
                |          Marker3 from the cMarkers collection. 
                |          
                | 
                |          Dim oMarker1 As Marker
                |          Set oMarker1 = cMarkers.Item(3)
                |          Dim oMarker2 As Marker
                |          Set oMarker2 = cMarkers.Item("Marker3")

        :param CATVariant i_index:
        :return: AnyObject
        """
        return self.com_object.Item(i_index)

    def remove(self, i_index: CATVariant) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub Remove(CATVariant iIndex)
                |     Removes a Marker from the Markers collection.
                | 
                |     Parameters:
                | 
                |         iIndex
                |             The index or the name of the Marker to retrieve from the collection
                |             of Markers. As a numerics, this index is the rank of the Marker in the
                |             collection. The index of the first Marker in the collection is 1, and the index
                |             of the last Marker is Count. As a string, it is the name you assigned to the
                |             Marker. 
                | 
                |     Example:
                | 
                |          The following example removes the second Marker and the Marker
                |          named
                |          Marker2 from the cMarkers collection.
                |          
                | 
                |          cMarkers.Remove(2)
                |          cMarkers.Remove("Marker2")

        :param CATVariant i_index:
        :return: None
        """
        return self.com_object.Remove(i_index)

    def __getitem__(self, n: int) -> Marker:
        if (n + 1) > self.count:
            raise StopIteration

        return Marker(self.com_object.Item(n + 1))

    def __iter__(self) -> Iterator[Marker]:
        for i in range(self.count):
            yield Marker(self.com_object.Item(i + 1))

    def __repr__(self):
        return f'Markers(name="{self.name}")'
