"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""

from pycatia3dx.system.any_object import AnyObject


class SrsBoundingBox(AnyObject):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     SrsBoundingBox
                | 
                | Object for SrsBoundingBox.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    def get_math_box(self) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Sub GetMathBox(CATSafeArrayVariant oMathBox)
                |     Get MathBox to a bounding box feature.
                |
                |     Parameters:
                |
                |         oMathBox
                |             bounding box which limits the space where the refence planes exist.
                |
                |
                |     Example:
                |
                |
                |              This example retrieves the bounding box feature.
                |
                |
                |               Dim oMathBox(5) As Variant
                |               ObjSrsBoundingBox.GetMathBox oMathBox.

        :return: tuple
        """
        return self.com_object.GetMathBox()
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'get_math_box'
        # vba_code = """
        # Public Function get_math_box(srs_bounding_box)
        #     Dim oMathBox (2)
        #     srs_bounding_box.GetMathBox oMathBox
        #     get_math_box = oMathBox
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def is_aft_at_origin(self) -> bool:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func IsAftAtOrigin() As boolean
                |     Gets the orientation of a shape representation of a ship.
                | 
                |     Returns:
                |         The orientation of the bounding box (TRUE means that orientation is the
                |         same as direction) 
                |     Example:
                | 
                | 
                |              This example retrieves the shape representation of a
                |              ship.
                |              
                | 
                |               Dim BoolIsAftAtOrigin As Boolean
                |               BoolIsAftAtOrigin = ObjSrsBoundingBox.IsAftAtOrigin

        :return: bool
        """
        return self.com_object.IsAftAtOrigin()

    def __repr__(self):
        return f'SrsBoundingBox(name="{self.name}")'
