"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""

from pycatia3dx.system.any_object import AnyObject


class SrsCoordinateConverter(AnyObject):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     SrsCoordinateConverter
                | 
                | Object for SrsCoordinateConverter.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    def convert_absolute_coord_to_srs_coord(self, i_x: float, i_y: float, i_z: float,
                                            olu_srs_coordinates: tuple) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub ConvertAbsoluteCoordToSrsCoord(double iX,double iY,double
                | iZ,CATSafeArrayVariant oluSrsCoordinates)
                |     Convert Absolute Coordinate To SRS Coordinate
                | 
                |     Parameters:
                | 
                |         iX
                |             [in] X coordinate expressed in absolute coordinate (in mm).
                |             
                |         iY
                |             [in] Y coordinate expressed in absolute coordinate (in mm).
                |             
                |         iZ
                |             [in] Z coordinate expressed in absolute coordinate (in mm).
                |             
                |         oluSrsCoordinates
                |             [out] SRS Coordinates as a list of strings (Plane name + distance
                |             to plane) with correct units. The order of the output is CROSS, LONG, DECK.
                |             
                | 
                |     Returns:
                |         Error code of function.

        :param float i_x:
        :param float i_y:
        :param float i_z:
        :param tuple olu_srs_coordinates:
        :return: None
        """
        return self.com_object.ConvertAbsoluteCoordToSrsCoord(i_x, i_y, i_z, olu_srs_coordinates)

    def convert_srs_coord_to_absolute_coord(self, ilu_srs_coordinates: tuple) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Sub ConvertSrsCoordToAbsoluteCoord(CATSafeArrayVariant iluSrsCoordinates,double
                | oX,double oY,double oZ)
                |     Convert SRS Coordinate To Absolute Coordinate
                |
                |     Parameters:
                |
                |         iluSrsCoordinates
                |             [in] SRS Coordinates as a list of strings (Plane name + distance to
                |             plane) with correct units. The order of the intput should be CROSS, LONG, DECK.
                |
                |         oX
                |             [out] X coordinate expressed in absolute coordinate (in mm).
                |
                |         oY
                |             [out] Y coordinate expressed in absolute coordinate (in mm).
                |
                |         oZ
                |             [out] Z coordinate expressed in absolute coordinate (in mm).
                |
                |
                |     Returns:
                |         Error code of function.

        :param tuple ilu_srs_coordinates:
        :return: tuple
        """
        return self.com_object.ConvertSrsCoordToAbsoluteCoord(ilu_srs_coordinates)
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'convert_srs_coord_to_absolute_coord'
        # vba_code = """
        # Public Function convert_srs_coord_to_absolute_coord(srs_coordinate_converter)
        #     Dim iluSrsCoordinates (2)
        #     srs_coordinate_converter.ConvertSrsCoordToAbsoluteCoord iluSrsCoordinates
        #     convert_srs_coord_to_absolute_coord = iluSrsCoordinates
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def __repr__(self):
        return f'SrsCoordinateConverter(name="{self.name}")'
