"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""

from pycatia3dx.space_reference_system.srs_grid_face import SrsGridFace
from pycatia3dx.system.any_object import AnyObject


class SrsMidShip(AnyObject):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     SrsMidShip
                | 
                | Role: Allows accessing of MidShip's data.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    @property
    def reference_plane(self) -> SrsGridFace:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property ReferencePlane() As SrsGridFace (Read Only)

        :return: SrsGridFace
        """

        return SrsGridFace(self.com_object.ReferencePlane)

    def get_front_orientation_direction(self) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Sub GetFrontOrientationDirection(CATSafeArrayVariant
                | oDirection)

        :return: tuple
        """
        return self.com_object.GetFrontOrientationDirection()
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'get_front_orientation_direction'
        # vba_code = """
        # Public Function get_front_orientation_direction(srs_mid_ship)
        #     Dim oDirection (2)
        #     srs_mid_ship.GetFrontOrientationDirection oDirection
        #     get_front_orientation_direction = oDirection
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def __repr__(self):
        return f'SrsMidShip(name="{self.name}")'
