"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""

from pycatia3dx.space_reference_system.srs_grid_face import SrsGridFace
from pycatia3dx.space_reference_system.srs_grid_faces import SrsGridFaces
from pycatia3dx.system.any_object import AnyObject


class SrsGridSet(AnyObject):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     SrsGridSet
                | 
                | Role: Allows accessing of Grid Set's data.
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    def get_direction(self) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub GetDirection(CATSafeArrayVariant oDirection)
                |     Gets direction of the grid set.
                | 
                |     Parameters:
                | 
                |         oDirection
                |             Direction of grid set. 
                | 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the direction of the grid
                |               set.
                |               
                | 
                |                Dim GridSetDirection(2) as Variant
                |                Set ObjHybridShapeDirection = ObjSrsGridSet.GetDirection GridSetDirection

        :return: tuple
        """
        # todo: check this method, does it require system service?
        return self.com_object.GetDirection()
        # # # # Autogenerated comment:
        # # some methods require a system service call as the methods expects a vb array object
        # # passed to it and there is no way to do this directly with python. In those cases the following code
        # # should be uncommented and edited accordingly. Otherwise, completely remove all this.
        # # vba_function_name = 'get_direction'
        # # vba_code = """
        # # Public Function get_direction(srs_grid_set)
        # #     Dim oDirection (2)
        # #     srs_grid_set.GetDirection oDirection
        # #     get_direction = oDirection
        # # End Function
        # # """

        # # system_service = SystemService(self.application.SystemService)
        # # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def get_extreme_faces(self, o_grid_face_bfr: SrsGridFace, o_grid_face_afr: SrsGridFace) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub GetExtremeFaces(SrsGridFace oGridFaceBfr,SrsGridFace
                | oGridFaceAfr)
                |     Gets the extreme faces in the grid set.
                | 
                |     Parameters:
                | 
                |         oGridFaceBfr
                |             Extreme Grid face present before the origin face in the grid set.
                |             
                |         oGridFaceAfr
                |             Extreme Grid face present after the origin face in the grid set.
                |             
                | 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the extreme grid faces in the grid
                |               set.
                |               
                | 
                |                Dim ObjSrsGridFaceBfr As SrsGridFace
                |                Dim ObjSrsGridFaceAfr As SrsGridFace
                |                ObjSrsGridSet.GetExtremeFaces ObjSrsGridFaceBfr
                |                ObjSrsGridFaceBfr

        :param SrsGridFace o_grid_face_bfr:
        :param SrsGridFace o_grid_face_afr:
        :return: None
        """
        return self.com_object.GetExtremeFaces(o_grid_face_bfr.com_object, o_grid_face_afr.com_object)

    def get_face(self, i_abs_offset: float, o_grid_face: SrsGridFace) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub GetFace(double iAbsOffset,SrsGridFace oGridFace)
                |     Gets the grid face at the given offset in the grid set.
                | 
                |     Parameters:
                | 
                |         iAbsOffset
                |             The absolute offset at which the face is located in the grid set.
                |             
                |         oGridFace
                |             The grid face at the given absolute offset. 
                | 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the grid faces at the given absolute
                |               offsetin the grid set.
                |               
                | 
                |                Dim AbsOffset As double
                |                Dim ObjSrsGridFace As SrsGridFace
                |                ObjSrsGridSet.GetFace AbsOffset ObjSrsGridFace

        :param float i_abs_offset:
        :param SrsGridFace o_grid_face:
        :return: None
        """
        return self.com_object.GetFace(i_abs_offset, o_grid_face.com_object)

    def get_faces(self) -> SrsGridFaces:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func GetFaces() As SrsGridFaces
                |     Returns all the faces in the grid set.
                | 
                |     Returns:
                |         The list of grid faces present in the grid set 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the grid faces in the grid
                |               set.
                |               
                | 
                |                Dim ObjSrsGridFaces As SrsGridFaces
                |                ObjSrsGridFaces = ObjSrsGridSet.GetFaces

        :return: SrsGridFaces
        """
        return SrsGridFaces(self.com_object.GetFaces())

    def get_faces_of_group(self, i_last_grid_face: SrsGridFace) -> SrsGridFaces:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func GetFacesOfGroup(SrsGridFace iLastGridFace) As
                | SrsGridFaces
                |     Returns the faces belonging to a particular group in the grid
                |     set.
                | 
                |     Parameters:
                | 
                |         iLastGridFace
                |             Last face of the group present in the grid set. 
                | 
                |     Returns:
                |         Faces belonging to the group. 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the faces belonging to a particular
                |               group.
                |               
                | 
                |                Dim ObjLastSrsGridFace As SrsGridFace
                |                Dim ObjSrsGridFacesGroup As SrsGridFaces
                |                ObjSrsGridSet.GetFacesOfGroup ObjLastSrsGridFace
                |                ObjSrsGridFacesGroup

        :param SrsGridFace i_last_grid_face:
        :return: SrsGridFaces
        """
        return SrsGridFaces(self.com_object.GetFacesOfGroup(i_last_grid_face.com_object))

    def get_faces_sorted(self, o_grid_faces_bfr: SrsGridFaces, o_origin_face: SrsGridFace,
                         o_grid_faces_afr: SrsGridFaces) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub GetFacesSorted(SrsGridFaces oGridFacesBfr,SrsGridFace
                | oOriginFace,SrsGridFaces oGridFacesAfr)
                |     Gets all the faces in the grid set.
                | 
                |     Parameters:
                | 
                |         oGridFacesBfr
                |             Grid faces present before the origin face in the grid set.
                |             
                |         oOriginFace
                |             Origin grid face of the grid set. 
                |         oGridFacesAfr
                |             Grid faces present after the origin face in the grid set.
                |             
                | 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the grid faces in the grid
                |               set.
                |               
                | 
                |                Dim ObjSrsGridFacesBfr As SrsGridFaces
                |                Dim ObjSrsOriginGridFace As SrsGridFace
                |                Dim ObjSrsGridFacesAfr As SrsGridFaces
                |                ObjSrsGridSet.GetFaces ObjSrsGridFacesBfr ObjSrsOriginGridFace
                |                ObjSrsGridFacesAfr

        :param SrsGridFaces o_grid_faces_bfr:
        :param SrsGridFace o_origin_face:
        :param SrsGridFaces o_grid_faces_afr:
        :return: None
        """
        return self.com_object.GetFacesSorted(o_grid_faces_bfr.com_object, o_origin_face.com_object,
                                              o_grid_faces_afr.com_object)

    def get_group_faces(self, o_last_grid_faces_bfr: SrsGridFaces, o_last_grid_faces_afr: SrsGridFaces) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub GetGroupFaces(SrsGridFaces oLastGridFacesBfr,SrsGridFaces
                | oLastGridFacesAfr)
                |     Gets group faces before and after the origin face in the grid
                |     set.
                | 
                |     Parameters:
                | 
                |         oLastGridFacesBfr
                |             Last faces of the groups present before the origin face in the grid
                |             set. 
                |         oLastGridFacesAfr
                |             Last faces of the groups present after the origin face in the grid
                |             set. 
                | 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves group faces present before and after the
                |               origin face in the grid set.
                |               
                | 
                |                Dim ObjSrsGridFacesBfr As SrsGridFaces
                |                Dim ObjSrsGridFacesAfr As SrsGridFaces
                |                ObjSrsGridSet.GetGroupFaces ObjSrsGridFacesBfr
                |                ObjSrsGridFacesAfr

        :param SrsGridFaces o_last_grid_faces_bfr:
        :param SrsGridFaces o_last_grid_faces_afr:
        :return: None
        """
        return self.com_object.GetGroupFaces(o_last_grid_faces_bfr.com_object, o_last_grid_faces_afr.com_object)

    def get_naming_prefix(self) -> str:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func GetNamingPrefix() As CATBSTR
                |     Returns the prefix of face's name.
                | 
                |     Returns:
                |         The prefix of the grid face's name 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves prefix of face's name.
                |               
                | 
                |                Dim ObjPrefix As String
                |                ObjPrefix = ObjSrsGridSet.GetNamingPrefix

        :return: str
        """
        return self.com_object.GetNamingPrefix()

    def get_nb_faces(self) -> int:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func GetNbFaces() As long
                |     Returns number of faces present in the grid set.
                | 
                |     Returns:
                |         The number of faces present in the grid set 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the number of faces in the grid
                |               set.
                |               
                | 
                |                Dim NbFaces As integer
                |                NbFaces = ObjSrsGridSet.GetNbFaces

        :return: int
        """
        return self.com_object.GetNbFaces()

    def get_nb_faces_sorted(self, o_nb_faces_bfr: int, o_origin_face_exist: bool, o_nb_faces_aft: int) -> None:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Sub GetNbFacesSorted(long oNbFacesBfr,boolean oOriginFaceExist,long
                | oNbFacesAft)
                |     Gets number of faces present before and after the origin face in the grid
                |     set.
                | 
                |     Parameters:
                | 
                |         oNbFacesBfr
                |             Number of faces present before the origin face in the grid set.
                |             
                |         oOriginFaceExist
                |             Origen Face exist in the grid set. 
                |         oNbFacesAft
                |             Number of faces present after the origin face in the grid set.
                |             
                | 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the faces before and after the origin face
                |               in the grid set.
                |               
                | 
                |                Dim NbFacesBfr As integer
                |                Dim OriginFaceExist As boolean
                |                Dim NbFacesAfr As integer
                |                ObjSrsGridSet.GetNbFaces NbFacesBfr OriginFaceExist
                |                NbFacesAfr

        :param int o_nb_faces_bfr:
        :param bool o_origin_face_exist:
        :param int o_nb_faces_aft:
        :return: None
        """
        return self.com_object.GetNbFacesSorted(o_nb_faces_bfr, o_origin_face_exist, o_nb_faces_aft)

    def get_orientation(self) -> bool:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func GetOrientation() As boolean
                |     Returns orientation of the Grid Set.
                | 
                |     Returns:
                |         The boolean whether the orientation is same as direction of the grid
                |         set (TRUE means that the orientation is same as direction)
                |         
                |     Example:
                | 
                |          
                | 
                |               This example retrieves orientation of the grid
                |               set.
                |               
                | 
                |                Dim Orientation As boolean
                |                Orientation = ObjSrsGridSet.GetOrientation

        :return: bool
        """
        return self.com_object.GetOrientation()

    def is_symmetric(self) -> bool:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func IsSymmetric() As boolean
                |     Returns whether the grid set is symmetric.
                | 
                |     Returns:
                |         The boolean whether the grid set is symmetric (TRUE means that the grid
                |         set is symmetric) 
                |     Example:
                | 
                |          
                | 
                |               This example retrieves the faces belonging to a particular
                |               group.
                |               
                | 
                |                Dim IsSymmetric As boolean
                |                IsSymmetric = ObjSrsGridSet.IsSymmetric 

        :return: bool
        """
        return self.com_object.IsSymmetric()

    def __repr__(self):
        return f'SrsGridSet(name="{self.name}")'
