"""
    Module initially auto generated using DSYAutomation files from CATIA 3DX R2025x on 2025-09-28 13:20:20.191090

    .. warning::
        The notes denoted "3DEXPERIENCE Automation Help" are to be used as reference only.
        They are there as a guide as to how the visual basic / catscript functions work
        and thus help debugging in pycatia.
        
"""

from pycatia3dx.system.any_object import AnyObject


class ExpertReportObject(AnyObject):
    """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)

                | SystemTS.IUnknown
                |     System.IDispatch
                |         System.CATBaseUnknown
                |             System.CATBaseDispatch
                |                 System.AnyObject
                |                     ExpertReportObject
                | 
                | Represents the ExpertReportObject object.
                | 
                | See also:
                |     ExpertReportObjects.Item, ExpertReportObjects.SucceedItem,
                |     ExpertReportObjects.FailItem
    
    """

    def __init__(self, com_object):
        super().__init__(com_object)
        self.com_object = com_object

    @property
    def validity(self) -> bool:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Property Validity() As boolean (Read Only)
                |     Returns the validity of a check for a given tuple. The result depends on
                |     the result of the check for a given tuple :
                | 
                |     "True" or "False" for the tuple.

        :return: bool
        """

        return self.com_object.Validity

    def get_tuple(self) -> tuple:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2026-02-08 14:05:01.675948))
                | Sub getTuple(CATSafeArrayVariant oSafeArray)
                |     Returns a tuple (a collection of objects) concerned by this report
                |     object.
                |
                |     Example:
                |
                |          Dim RuleBase1 As ExpertRuleBaseRuntime
                |          Set RuleBase1 = ...
                |
                |          Dim ListComponents As ExpertRuleBaseComponentRuntimes
                |          Set ListComponents = RuleBase1.RuleSet.ExpertRuleBaseComponentRuntimes
                |
                |          ' Let's get a check ..
                |          Dim AComponent As ExpertRuleBaseComponentRuntime
                |          Set AComponent = ListComponents.Item("CheckOnHoles")
                |
                |          ' .. and let's see what makes it true
                |          Dim NupletsList As ExpertReportObjects
                |          Set NupletsList = AComponent.Succeeds
                |
                |          Dim ANuplet As ExpertReportObject
                |          Dim anArray () as Object
                |          Dim anElementArray as Object
                |
                |          For i = 1 to AComponent.Succeeds.CountSucceed
                |            Set ANuplet = AComponent.Succeeds.SucceedItem(i)
                |            NupletSize = ANuplet.getTupleSize()
                |            ReDim anArray (NupletSize)
                |            ANuplet.getTuple(anArray)
                |            For j = LBound(anArray) to UBound(anArray)
                |              Set anElementArray = anArray(j) ' a hole
                |
                |              ' .. some action on the element of the array
                |            Next
                |          Next
                |
                |
                |     Parameters:
                |
                |         oSafeArray
                |             The collection of objects.

        :return: tuple
        """
        return self.com_object.getTuple()
        # todo: check this method, does it require system service?
        # Autogenerated comment:
        # some methods require a system service call as the methods expects a vb array object
        # passed to it and there is no way to do this directly with python. In those cases the following code
        # should be uncommented and edited accordingly. Otherwise completely remove all this.
        # vba_function_name = 'get_tuple'
        # vba_code = """
        # Public Function get_tuple(expert_report_object)
        #     Dim oSafeArray (2)
        #     expert_report_object.getTuple oSafeArray
        #     get_tuple = oSafeArray
        # End Function
        # """

        # system_service = SystemService(self.application.SystemService)
        # return system_service.evaluate(vba_code, 0, vba_function_name, [self.com_object])

    def get_tuple_size(self) -> int:
        """
        .. note::
            :class: toggle

            3DEXPERIENCE Automation Help (2025-09-28 13:20:20.191090)
                | Func getTupleSize() As long
                |     Returns the size of the tuple concerned by this report
                |     object.
                | 
                |     Returns:
                |         Size of the tuple

        :return: int
        """
        return self.com_object.getTupleSize()

    def __repr__(self):
        return f'ExpertReportObject(name="{self.name}")'
